### ISSUE TITLE
Database too large to compile using msa package in Rstudio

### ISSUE THREAD

**Issue by Sapienscyclistus** [moyn413/nifHdada2#1]
Hello and thanks for your work. 

I am currently working with your dada2 formated database and i'd like to run a multiple sequence alignment on it. 
I am using the msa package and managed to perform a ClustalOmega on the database (as the ClustalW is still working on it more than 10hours later). 

I'd like to use the msaprettyprint function of the msa package but the problem is that the file is too large apparently for the texi2dvi to tranform the .tex file in .pdf 

If you have any suggestion/help on what I could do to make this work, it would be greatly appreciated. 

Many thanks in advance

**Comment by moyn413** [comment]
Hi, apologies for the slow response time. I've never had much luck doing multiple sequence alignments quickly in R, especially with large datasets, so I don't have any suggestions to help there. Have you tried with just a few sequences of interest?  

I was able to do a MAFFT alignment in about 5 minutes on the entire database using Geneious Prime.  I think MEGA should also have similar functionality. If you don't have access to the software, I would be happy to share the alignment output file.
